services:
  backup:
    environment:
      OFFSITE_BACKUP_DIR: /offsite_backups
    volumes:
      - offsite_data:/offsite_backups
      - ./scripts/restore.sh:/usr/local/bin/restore.sh:ro

volumes:
  offsite_data:
