package com.eneik.epidemiology.document;

import com.eneik.epidemiology.security.JwtTokenProvider;
import com.eneik.epidemiology.user.User;
import com.eneik.epidemiology.user.UserRepository;
import com.eneik.epidemiology.user.UserService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.HttpHeaders;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.transaction.annotation.Transactional;

import static org.hamcrest.Matchers.not;
import static org.hamcrest.Matchers.containsString;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest
@AutoConfigureMockMvc
@Transactional
class DocumentDownloadNonExistenceVerificationTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private UserService userService;

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private JwtTokenProvider jwtTokenProvider;

    private String researcherToken;

    @BeforeEach
    void setUp() {
        userRepository.deleteAll();
        User researcherUser = userService.createUser("strict_404_tester", "ResPass123!", "RESEARCHER");
        researcherToken = jwtTokenProvider.generateToken(researcherUser.getUsername(), researcherUser.getRole());
    }

    @Test
    @DisplayName("Given a download request for a non-existent document ID, When executed, Then backend returns 404 NOT FOUND status and empty or standard error body without generated byte content")
    void testDownloadNonExistentDocument_ReturnsStrict404WithoutGeneratedByteContent() throws Exception {
        Long nonExistentDocId = 999999L;

        mockMvc.perform(get("/api/v1/documents/" + nonExistentDocId + "/download")
                        .header(HttpHeaders.AUTHORIZATION, "Bearer " + researcherToken))
                .andExpect(status().isNotFound())
                .andExpect(content().string(not(containsString("Содержимое документа"))));
    }
}
