ALTER TABLE telemetry_events ADD COLUMN IF NOT EXISTS workflow_duration_ms BIGINT;
ALTER TABLE telemetry_events ADD COLUMN IF NOT EXISTS start_time TIMESTAMP WITH TIME ZONE;
ALTER TABLE telemetry_events ADD COLUMN IF NOT EXISTS end_time TIMESTAMP WITH TIME ZONE;
